teleop_twist_joy_node:
  ros__parameters:
    enable_button: 4
    # enable_turbo_button: 5
    axis_linear:
      x: 4
    axis_angular:
      yaw: 0

    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 0.7
    scale_linear:
      x: 2.6    # was 0.8
    scale_linear_turbo:
      x: 1.2

joy_node:
  ros__parameters:
    deadzone: 0.1
    device_id: 0
    device_name: ''
