global_planner:
  ros__parameters:
    # === MAP PARAMETERS ===
    map_name: "levine/levine_map"                # Folder name under maps/
    map_dir: "./maps/"                # Relative or absolute path
    create_map: False                 # Generate centerline from png
    show_plots: True                 # Show matplotlib figures

    # === TRACK AND CENTERLINE SETTINGS ===
    filter_kernel_size: 7             # Image blur kernel (odd number)
    safety_width: 0.15                # Safety margin (m)
    safety_width_sp: 0.25             # For shortest path
    resample_step: 0.1                # Step for centerline resampling
    required_laps: 1

    # === GLOBAL TRAJECTORY SETTINGS ===
    max_speed: 15.0                    # Target max velocity [m/s]
    min_speed: 0.5
    max_accel: 3.0                    # [m/s^2]
    max_decel: -3.0
    curvature_gain: 1.0               # vx = max_speed / (1 + curvature_gain * |kappa|)
    smooth_window: 7                  # Moving average window for smoothing
    traj_type: "iqp"                  # "iqp" (curvature-opt) or "sp" (shortest-path)
    save_json: True                   # Save global_waypoints.json
    publish_rate: 10.0                # Hz
    rate: 10.0

    # === OUTPUT FILE PATHS ===
    save_centerline_csv: "./maps/map_centerline.csv"
    save_json_path: "./maps/global_waypoints.json"

    # === VISUALIZATION ===
    publish_markers: True
    publish_debug: False
